SHOW CON_NAME;
SHOW pdbs

ALTER SESSION SET CONTAINER = XEPDB1;

DEFINE user = id_tp_md
-- USER SQL
CREATE USER &user. IDENTIFIED BY &user.
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER &user. QUOTA UNLIMITED ON "USERS";

-- ROLES
GRANT "CONNECT" TO &user.;
GRANT "RESOURCE" TO &user.;